### ISSUE TITLE
Atomic parsley problem

### ISSUE THREAD

**Issue by golden-grace** [get-iplayer/get_iplayer#169] opened 2015-06-15 10:43 UTC
Ever since I upgraded to 2.94 after every download a series of error messages come up saying the version of atomicparsley.exe is incompatible with 64 bit windows 7.  Any ideas?

**Comment by dinkypumpkin** [comment] 2015-06-15 10:55
Duplicate of #166

**Closed by dinkypumpkin** 2015-06-15 10:55 UTC

**Comment by golden-grace** [comment] 2015-06-15 10:59
It seems a bit odd that we should be getting the same problem, but you are dismissing it as a fault on my system.  I could follow your advice to post on the forums (maybe that is what you mean) but sorry if I am being thick, but I can't see how to place a new post?

**Comment by dinkypumpkin** [comment] 2015-06-15 11:19
Well, until somebody finds a general problem, it is by definition a fault on your system (and the system of one other person).  I already said I can't duplicate the problem, and in the absence of any other reports I have to assume that it is working OK for all the other users of 64-bit Windows, so I can't help you.

You have to enter a forum to create a new topic. After you log in, click on the "Windows Troubleshooting" forum in the forum list on the main forums page (accessed via "Support" link in nav bar) and you'll see text boxes for topic title and text at the bottom of the page. Make your entries and click "Submit".

**Comment by golden-grace** [comment] 2015-06-15 12:09
Got it!  Done, posted thanks.
