### ISSUE TITLE
Deprication warning in the maintenance message

### ISSUE THREAD

**Issue by xplora1a** [get-iplayer/get_iplayer#257] opened 2016-04-05 06:37 UTC
<h1>Maintenance mode</h1>
<p>This service is currently undergoing a period of downtime for essential maintenance.</p>
<h2>Deprecation Warning</h2>
<p>Please be advised that the programme information service which is currently available at this URL will soon be replaced by a fully-supported public instance of the Nitro API, whose principles and point of
contact are described here: <a href='https://developer.bbc.co.uk/nitro'>https://developer.bbc.co.uk/nitro</a>.<br /> In the meantime, if you have any queries about the existing service, please contact the following email address for further information: 'programmes-devel@lists.forge.bbc.co.uk'</p>

**Comment by dinkypumpkin** [comment] 2016-04-05 09:20
Duplicate of #239

**Closed by dinkypumpkin** 2016-04-05 09:20 UTC
