### ISSUE TITLE
New BBC Program Information Service

### ISSUE THREAD

**Issue by j1mr10rd4n** [get-iplayer/get_iplayer#252] opened 2016-02-14 22:17 UTC
I'm unable to add this comment to #239, but thought it would be worth capturing.

Visiting any of the (currently broken) programme schedule URLs gives the following message:

e.g. http://www.bbc.co.uk/bbcnews/programmes/schedules/last_week.xml

> This service is currently undergoing a period of downtime for essential maintenance. Please be advised that the programme information service which is currently available at this URL will soon be replaced by a new service from the BBC, at a new set of URLs. Please contact the following email address for further information: 'programmes-devel@lists.forge.bbc.co.uk'

**Comment by dinkypumpkin** [comment] 2016-02-14 22:18
Duplicate of #251

**Closed by dinkypumpkin** 2016-02-14 22:18 UTC
Labels: duplicate
