### ISSUE TITLE
Only audio described version is downloading

### ISSUE THREAD

**Issue by donnatellamoss** [get-iplayer/get_iplayer#116] opened 2015-01-17 19:12 UTC
In brief: get_iplayer is occasionally (but not always) downloading audio described version as the default but I want it to download the SD as default. Please help.

Details:

I have been having this issue for a couple of months on a few programs but I haven't been able to find the answer on the forums yet.  I did see post #115 but don't know how to use the work around to apply it to my problem.

Most recently I have tried to download The Musketeers Series 2 episode 3. I want the SD version, which get_iplayer usually downloads by default, but when I try to download it, get_iplayer downloads the audiodescribed version as the default. Is there a way of telling get_iplayer to choose the SD version?

I have tried the following commands:
get_iplayer --pid b04ykm2t
get_iplayer "http://www.bbc.co.uk/iplayer/episode/b04ykm2t/the-musketeers-series-2-3-the-good-traitor"
get_iplayer --get 1661
I have also tried the PVR manager (audio described is not selected as default version) but each time it downloads the audio described version.

I then updated to get_iplayer 2.91 just in case that solved the problem, but then whichever command I used I got the following message:

INFO: File name prefix = The_Musketeers_Series_2_ -_3._The_Good_Traitor_b04ykm2t_audiodescribed
RTMPDump v2.4
2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
ERROR: Last tag size must be greater/equal zero and smaller then file size, corrupt file!
INFO: Command exit code 1
WARNING: Retry recording for 'The Musketeers Series 2 - 3. The Good Traitor '

I do not get this problem on all programs, just a handful. I download about 1 program per day and have only come across this issue twice since the beginning of January. The last time was trying to download Casualty Series 29 episode 15 (broadcast Jan 3rd). I spent all week trying to get it to download the standard version but I could only get the audio decribed version even though the SD version was available on the iplayer website. Because this program is still available on the bbc iplayer website I had another go at downloading it using command: get_iplayer --pid b04xwwxn --force. This time it downloaded the SD version for me.

At this point I realised I had been a numptie and hadn't deleted the previous attempt at downloading The Musketeers from my iPlayer Recordings folder before trying again using get_iplayer 2.91 and realised this may be the reason I got the error message above. I tried downloading again using command: get_iplayer --pid b04ykm2t --force, but as before, it downloaded the audio described version. I also tried using --modes=flashhigh, but it still downloaded the audio described version

I know how to get get_iplayer to download the audio described version instead of the SD version, but is there a way of telling get_iplayer to download the SD version (or even the HD version would do) and ignore audio described?

**Comment by dinkypumpkin** [comment] 2015-01-17 20:00
Duplicate of #115.  I can't add any further explanation to the workaround described there.  You obviously know how to formulate a get_player command, so just add the option indicated.

**Closed by dinkypumpkin** 2015-01-17 20:00 UTC
Labels: duplicate
